### DISCUSSION TITLE
Your mysql client library does not support ssl_mode as expected.

### DISCUSSION THREAD

**Discussion by Overload119** [planetscale/discussion#110] [Bug Reports] [answered]
I'm using Rails and `gem 'mysql2', '~> 0.5'`

In my database.yml file:

```
XXX:
    <<: *default
    database: XXX
    username: XXX
    host: XXX
    password: XXX
    ssl_mode: :verify_identity
    sslca: /etc/ssl/certs/ca-certificates.crt
    migrations_paths: db/leads_migrate
```

There is no actual problems (I can write and read database fine). I was just wondering how one would go about debugging this error.
