### DISCUSSION TITLE
SSL/TLS required for gitea

### DISCUSSION THREAD

**Discussion by mpilosov** [planetscale/discussion#273] [Q&A] [answered]
Hello, I am trying to configure [`gitea`](docs.gitea.io) to use planetscale and am finding that I get this error (which I found mentioned in discussions here). 
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16293134/188502428-a9615574-8a45-4053-992d-3cd7f5a1abd3.png">

I have tried setting `SSL_MODE=true` as documented here https://docs.gitea.io/en-us/config-cheat-sheet/#database-database but am still not able to connect. Is there some way to configure gitea to communicate with planetscale?

for reproducibility:

```
version: "3"

services:
  server:
    image: gitea/gitea:1.17.1
    container_name: remote-gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=us-west.connect.psdb.cloud  # is this correct or am I missing a subdomain?
      - GITEA__database__NAME=<NAME>
      - GITEA__database__USER=<USER>
      - GITEA__database__PASSWD=<PASS>
      - GITEA__database__SSL_MODE=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"

networks:
  gitea:
    external:
      name: git-network
```
