### DISCUSSION TITLE
How do I use the Docker Image for a Docker Compose service?

### DISCUSSION THREAD

**Discussion by CompeyDev** [planetscale/discussion#320] [Q&A]
I want to be able to use the Pscale CLI inside a Docker container using the image using a configuration similar to below:
```yml
services:
  mysql:
    image: planetscale/pscale
    command: "pscale connect XXXX"
```

However, once the image is built- before I can provide arguments or run an actual command, the CLI will just display a help menu and exit with a code of 0. How do I pass arguments to the image and keep it active after (so that I can connect to it using another service)?
