### DISCUSSION TITLE
Can not found source database when do `pscale create branch` on github actions

### DISCUSSION THREAD

**Discussion by ytnobody** [planetscale/discussion#552] [Q&A]
I encountered below error on a github actions workflow.

```
Run pscale branch create my_app_db ci-10c37bc4a798cca3b[2](https://github.com/my-org/my-app/actions/runs/6502530552/job/17661921839#step:13:2)5f78ca36a83ab64fb51106 --org my-org --wait 
  pscale branch create my_app_db ci-10c37bc4a798cca3b25f78ca36a83ab64fb51106 --org my-org --wait 
  shell: /usr/bin/bash -e {0}
  env:
    PLANETSCALE_SERVICE_TOKEN_ID: ***
    PLANETSCALE_SERVICE_TOKEN: ***
Creating branch from my_app_db...
Error: source database my_app_db does not exist in organization my-org
Error: Process completed with exit code 2.
```

And, this is a github workflow setting yml file.

```
name: "check-server"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pscale
        uses: planetscale/setup-pscale-action@v1

      - name: Create a branch on PlanetScale
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: |
          pscale branch create my_app_db ci-${{ github.sha }} --org my-org --wait 

        ...
```

And conditions is below.

- Database `my_app_db` exists in organization `my-org`.
- Plan of `my_app_db` is `Hobby`.
- A service token has below permissions with database `my_app_db`.
  - `connect_branch`
  - `create_branch`
  - `delete_branch`
  - `read_branch`
  - `read_database`
  - `write_database`

What can I do to resolve this error?
